imports:
  - { resource: services.yml }
  - { resource: doctrine.yml }
  - { resource: logger.yml }
#  - { resource: doctrine_cache.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
  #esi: ~
  #translator: { fallbacks: ['%locale%'] }
  secret: '%secret%'
  router:
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  #serializer: { enable_annotations: true }
  default_locale: '%locale%'
  session:
    # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    handler_id:  session.handler.native_file
    save_path:   "%kernel.project_dir%/var/sessions/%kernel.environment%"
  fragments: ~
  http_method_override: true
  assets: ~
  php_errors:
      log: true

swiftmailer:
    transport: '%mailer_transport%'
    local_domain: '%mailer_local_domain%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
