doctrine:
  dbal:
    mapping_types:
      enum: string
    types:
      datetime: Ivoz\Core\Infrastructure\Persistence\Doctrine\Model\DBAL\Types\UtcDateTimeType
      datetimetz: Ivoz\Core\Infrastructure\Persistence\Doctrine\Model\DBAL\Types\UtcDateTimeType
      decimal: Ivoz\Core\Infrastructure\Persistence\Doctrine\Model\DBAL\Types\NumericDecimalType
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    quote_strategy: 'Ivoz\Core\Infrastructure\Persistence\Doctrine\ORM\Mapping\QuoteStrategy'
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: yes