monolog:
 channels: ['changelog', 'provisioning']
 handlers:
   filter_for_errors:
     type: fingers_crossed
     action_level: error
     priority: 1
     handler: fingers_crossed_handler
     buffer_size: 100
     channels: ["!changelog", "!provisioning"]
     excluded_http_codes: [404]

   fingers_crossed_handler:
     ident: php.onError
     type: syslog
     level: info
     buffer_size: 100

   changelog_handler:
     ident: php.changelog
     type: syslog
     level: info
     priority: 10
     channels: changelog

   provisioning_handler:
     ident: php.provisioning
     type: syslog
     level: info
     priority: 10
     channels: provisioning
