imports:
  - { resource: 'services/infraestructure.yml' }
  - { resource: 'services/entities.yml' }
  - { resource: "services/assemblers.yml" }
  - { resource: "services/events.yml" }
  - { resource: "services/application.yml" }
  - { resource: 'lifecycle.yml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ivoz\Core\Infrastructure\Symfony\EventListener\DomainExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, priority: 1 }

  Ivoz\Core\Infrastructure\Symfony\HttpFoundation\RequestDateTimeResolver: ~

  Ivoz\CoreBundle\Command\:
    resource: '%kernel.project_dir%/vendor/irontec/ivoz-core-bundle/Command/*'
    tags: [{ name: 'console.command'}]
