services:
  _defaults:
    autowire: true
    public: true

  Ivoz\Core\Domain\Service\QueryBuilderFactory:
    arguments:
      $entityManager: "@doctrine.orm.entity_manager"

  Ivoz\Core\Application\Service\DataGateway:
    arguments:
      $entityManager:
        "@doctrine.orm.entity_manager"
