services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ivoz\Core\Infrastructure\Application\DoctrineForeignKeyTransformer:
    arguments:
    - '@doctrine.orm.entity_manager'

  Ivoz\Core\Domain\ForeignKeyTransformerInterface:
    '@Ivoz\Core\Infrastructure\Application\DoctrineForeignKeyTransformer'

  Ivoz\Core\Infrastructure\Application\DoctrineCollectionTransformer:
    arguments:
    - '@doctrine.orm.entity_manager'

  Ivoz\Core\Domain\Model\EntityInterface\CollectionTransformerInterface:
    '@Ivoz\Core\Infrastructure\Application\DoctrineCollectionTransformer'

  core.doctrine_collection_transformer:
    '@Ivoz\Core\Infrastructure\Application\DoctrineCollectionTransformer'

  Ivoz\Core\Domain\Service\CreateEntityFromDto: ~

  core.create_entity_from_dto: '@Ivoz\Core\Domain\Service\CreateEntityFromDto'

  Ivoz\Core\Domain\Service\UpdateEntityFromDto:
    public: true

  core.update_entity_from_dto:
    class: Ivoz\Core\Domain\Service\UpdateEntityFromDto

  Ivoz\Core\Domain\Service\EntityPersisterInterface:
    '@Ivoz\Core\Infrastructure\Domain\Service\DoctrineEntityPersister'

  Ivoz\Core\Domain\Service\EntityTools:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'
    public: true
    lazy: true
