services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ivoz\Core\Domain\RequestId:
    public: true

  Ivoz\Core\Domain\Service\CommandEventSubscriber: ~

  Ivoz\Core\Domain\Service\EntityEventSubscriber:
    public: true

  # DomainEventPublisher calls are autocompleted on cache regenerations (Compiler fase)
  Ivoz\Core\Domain\Service\DomainEventPublisher:
     shared: true
     public: true
     calls:
      - [subscribe, ['@Ivoz\Core\Domain\Service\CommandEventSubscriber']]
      - [subscribe, ['@Ivoz\Core\Domain\Service\EntityEventSubscriber']]
