imports:
  - { resource: 'infraestructure/cgrates.yml' }
  - { resource: 'infraestructure/filesystem.yml' }
  - { resource: 'infraestructure/doctrine.yml' }
  - { resource: 'infraestructure/http.yml' }
  - { resource: 'infraestructure/kam.yml' }
  - { resource: 'infraestructure/mailer.yml' }
  - { resource: 'infraestructure/redis.yml' }
  - { resource: 'infraestructure/rest.yml' }
  - { resource: 'infraestructure/symfony.yml' }
