services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ivoz\Core\Infrastructure\Persistence\Doctrine\ORM\EntityManager:
    parent: 'doctrine.orm.entity_manager.abstract'
    autowire: false
    autoconfigure: false
    public: false
    factory:
      - 'Ivoz\Core\Infrastructure\Persistence\Doctrine\ORM\EntityManager'
      - 'create'
    arguments:
      $conn: '@doctrine.dbal.default_connection'
      $config: '@doctrine.orm.default_configuration'

  doctrine.orm.default_entity_manager:
    alias: Ivoz\Core\Infrastructure\Persistence\Doctrine\ORM\EntityManager
    public: true
    
  Ivoz\Core\Infrastructure\Persistence\Doctrine\ORM\Mapping\QuoteStrategy: ~

  core.doctrine_foreign_key_transformer:
    '@Ivoz\Core\Infrastructure\Application\DoctrineForeignKeyTransformer'

  core.doctrine_collection_transformer:
    '@Ivoz\Core\Infrastructure\Application\DoctrineCollectionTransformer'

  Ivoz\Core\Infrastructure\Domain\Service\DoctrineEntityPersister:
    arguments:
      $softDeleteMap: '%soft_delete%'
    public: true
    lazy: true

  Ivoz\Core\Infrastructure\Domain\Service\DoctrineQueryRunner: ~
