services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\CgrRpcClient:
    factory: ['Ivoz\Core\Infrastructure\Domain\Service\Cgrates\CgrRpcClient', 'factory']
    arguments: ['trunks.ivozprovider.local:2080/jsonrpc']

  Graze\GuzzleHttp\JsonRpc\ClientInterface:
    alias: 'Ivoz\Core\Infrastructure\Domain\Service\Cgrates\CgrRpcClient'

when@test:
  services:
    _defaults:
      autowire: true
      autoconfigure: true
      public: false

    Ivoz\Core\Infrastructure\Domain\Service\Cgrates\FakeCgrRpcClient: ~
    Graze\GuzzleHttp\JsonRpc\ClientInterface:
      alias: 'Ivoz\Core\Infrastructure\Domain\Service\Cgrates\FakeCgrRpcClient'
