services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Symfony\Component\Mailer\Mailer: ~

  Ivoz\Core\Infrastructure\Domain\Service\Mailer\Client:
    arguments:
      $mailer: '@Symfony\Component\Mailer\Mailer'

  Ivoz\Core\Domain\Service\MailerClientInterface:
    '@Ivoz\Core\Infrastructure\Domain\Service\Mailer\Client'

when@test:
  services:
    _defaults:
      autowire: true
      autoconfigure: true
      public: false

    Ivoz\Core\Infrastructure\Domain\Service\Mailer\FakeClient: ~
    Ivoz\Core\Domain\Service\MailerClientInterface:
      '@Ivoz\Core\Infrastructure\Domain\Service\Mailer\FakeClient'
