services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ivoz.api_platform.http.client:
    class: GuzzleHttp\Client
    arguments:
      $config:
        base_uri: '%api_platform_base_url%'
        timeout: 0
        allow_redirects: true
        verify: false

  Ivoz\Core\Infrastructure\Service\Rest\Client:
    arguments:
      $platformHttpClient: '@ivoz.api_platform.http.client'
      $jwtTokenManager: '@lexik_jwt_authentication.jwt_manager'

  Ivoz\Core\Domain\Service\ApiClientInterface:
    '@Ivoz\Core\Infrastructure\Service\Rest\Client'

when@test:
  services:
    _defaults:
      autowire: true
      autoconfigure: true
      public: false

    Ivoz\Core\Infrastructure\Service\Rest\FakeClient: ~
    Ivoz\Core\Domain\Service\ApiClientInterface:
      '@Ivoz\Core\Infrastructure\Service\Rest\FakeClient'