services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ivoz.api_platform.http.client:
    class: GuzzleHttp\Client
    arguments:
      $config:
        base_uri: '%api_platform_base_url%'
        timeout: 0
        allow_redirects: true
        verify: false
